### ISSUE TITLE
Live demo available?

### ISSUE THREAD

**Issue by CarMoreno** [FriOne/ng-push-notification#3]
Hi, Where can I see live demo for this package?, The target is implement notifications push in my angular 5 app like looks mobile push notifications. With this package I can achieve it?

**Comment by FriOne** [comment]
Sorry, there is no demo. I guess you can't make push notifications that work like native(when app closed you don't receive a push) with this library. You can do it with service worker, look at [this](https://developers.google.com/web/fundamentals/push-notifications/). But I think it will not work with iOS.
